#!/bin/bash
# tests/docker/coordinator-planning-tests.sh
# Phase 8.1 :: P0 - Dynamic Planning via Anthropic API (Coordinator V3)
# Tests coordinator's ability to decompose tasks into atomic units via API calls

set -euo pipefail

PROJECT_ROOT=$(git rev-parse --show-toplevel)
source "$PROJECT_ROOT/tests/test-utils.sh"

COORDINATOR_IMAGE="cfn-coordinator:v3"
TEST_TASK_ID="plan-test-$(date +%s)"
TMP_PLAN_FILE="/tmp/cfn-docker-plan-${TEST_TASK_ID}.json"
TEST_CONTAINER_NAME="cfn-coordinator-${TEST_TASK_ID}"

cleanup() {
  log_step "Cleaning up test artifacts"
  docker rm -f "$TEST_CONTAINER_NAME" 2>/dev/null || true
  rm -f "$TMP_PLAN_FILE" 2>/dev/null || true
}
trap cleanup EXIT

# Test 1: Planning Phase Calls Anthropic API
test_planning_phase_calls_api() {
  log_test_header "Test 1: Planning phase executes API call"

  # GIVEN coordinator with ANTHROPIC_API_KEY
  if [[ -z "${ANTHROPIC_API_KEY:-}" ]]; then
    log_error "ANTHROPIC_API_KEY not set, skipping API test"
    return 0
  fi

  log_step "GIVEN coordinator container with API key"
  local task_desc="Build JWT authentication service with backend API and React login form"

  # WHEN task description provided and planning phase executes
  log_step "WHEN coordinator plans task via API"
  docker run --rm \
    --name "$TEST_CONTAINER_NAME" \
    --network mcp-network \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v "$(pwd):/app/codebase:ro" \
    -v /tmp:/tmp \
    -e "ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}" \
    -e "TASK_ID=${TEST_TASK_ID}" \
    -e "TASK_DESCRIPTION=${task_desc}" \
    -e "MODE=standard" \
    -e "CFN_REDIS_HOST=cfn-redis" \
    -e "CFN_REDIS_PORT=6379" \
    -e "MAX_ITERATIONS=1" \
    "$COORDINATOR_IMAGE" > /tmp/coordinator-planning-output.log 2>&1 || true

  # THEN plan file created at expected location
  log_step "THEN plan file exists at /tmp/cfn-docker-plan-*.json"
  if [[ -f "$TMP_PLAN_FILE" ]]; then
    log_success "Plan file created: $TMP_PLAN_FILE"
  else
    log_error "Plan file not found: $TMP_PLAN_FILE"
    log_info "Coordinator output:"
    cat /tmp/coordinator-planning-output.log | head -50
    return 1
  fi

  # THEN plan file is valid JSON
  log_step "THEN plan file is valid JSON"
  if jq empty "$TMP_PLAN_FILE" 2>/dev/null; then
    log_success "Plan file is valid JSON"
  else
    log_error "Plan file is not valid JSON"
    cat "$TMP_PLAN_FILE"
    return 1
  fi

  log_success "✅ Test 1 PASSED: Planning phase calls API and generates plan file"
}

# Test 2: Plan File Has Correct Atomic Task Structure
test_plan_file_has_atomic_tasks() {
  log_test_header "Test 2: Plan file structure validation"

  # GIVEN plan file generated by planning phase
  if [[ ! -f "$TMP_PLAN_FILE" ]]; then
    log_error "Plan file not found from Test 1, skipping structure test"
    return 0
  fi

  log_step "GIVEN plan file from planning phase"

  # THEN file contains atomic_tasks array
  log_step "THEN plan has atomic_tasks array"
  local atomic_tasks_count=$(jq -r '.atomic_tasks | length' "$TMP_PLAN_FILE" 2>/dev/null || echo "0")
  if [[ "$atomic_tasks_count" -gt 0 ]]; then
    log_success "Found $atomic_tasks_count atomic tasks"
  else
    log_error "No atomic_tasks array found in plan file"
    cat "$TMP_PLAN_FILE"
    return 1
  fi

  # THEN each task has required fields
  log_step "THEN each task has: id, description, estimated_time, dependencies, agent_type, deliverables"
  local task_index=0
  while [[ $task_index -lt $atomic_tasks_count ]]; do
    local task=$(jq -r ".atomic_tasks[$task_index]" "$TMP_PLAN_FILE")

    local task_id=$(echo "$task" | jq -r '.id // "missing"')
    local description=$(echo "$task" | jq -r '.description // "missing"')
    local estimated_time=$(echo "$task" | jq -r '.estimated_time // "missing"')
    local dependencies=$(echo "$task" | jq -r '.dependencies // "missing"')
    local agent_type=$(echo "$task" | jq -r '.agent_type // "missing"')
    local deliverables=$(echo "$task" | jq -r '.deliverables // "missing"')

    if [[ "$task_id" == "missing" ]] || [[ "$description" == "missing" ]] || \
       [[ "$estimated_time" == "missing" ]] || [[ "$dependencies" == "missing" ]] || \
       [[ "$agent_type" == "missing" ]] || [[ "$deliverables" == "missing" ]]; then
      log_error "Task $task_index missing required fields"
      echo "$task" | jq .
      return 1
    fi

    log_info "Task $task_index: $task_id ($agent_type) - $description"
    task_index=$((task_index + 1))
  done

  log_success "✅ Test 2 PASSED: Plan file has correct atomic task structure"
}

# Test 3: Atomic Tasks Within Time Bounds
test_atomic_tasks_within_time_bounds() {
  log_test_header "Test 3: Atomic task time bounds validation"

  # GIVEN plan file with atomic tasks
  if [[ ! -f "$TMP_PLAN_FILE" ]]; then
    log_error "Plan file not found from Test 1, skipping time bounds test"
    return 0
  fi

  log_step "GIVEN atomic tasks in plan file"
  local atomic_tasks_count=$(jq -r '.atomic_tasks | length' "$TMP_PLAN_FILE")

  # THEN all tasks have estimated_time between 15-30 min
  log_step "THEN all tasks have estimated_time between 15-30 min"
  local task_index=0
  local violations=0

  while [[ $task_index -lt $atomic_tasks_count ]]; do
    local estimated_time=$(jq -r ".atomic_tasks[$task_index].estimated_time" "$TMP_PLAN_FILE")
    local task_id=$(jq -r ".atomic_tasks[$task_index].id" "$TMP_PLAN_FILE")

    # Extract numeric value (handles "25 min", "30min", etc.)
    local time_value=$(echo "$estimated_time" | grep -oE '[0-9]+' | head -1)

    if [[ -z "$time_value" ]]; then
      log_error "Task $task_id: Cannot parse estimated_time: $estimated_time"
      violations=$((violations + 1))
    elif [[ $time_value -lt 15 ]] || [[ $time_value -gt 30 ]]; then
      log_error "Task $task_id: Time $time_value min outside bounds [15-30]"
      violations=$((violations + 1))
    else
      log_info "Task $task_id: $time_value min ✓"
    fi

    task_index=$((task_index + 1))
  done

  if [[ $violations -eq 0 ]]; then
    log_success "✅ Test 3 PASSED: All $atomic_tasks_count tasks within 15-30 min bounds"
  else
    log_error "❌ Test 3 FAILED: $violations tasks outside time bounds"
    return 1
  fi
}

# Test 4: Fallback Behavior Without API Key
test_fallback_without_api_key() {
  log_test_header "Test 4: Planning fallback without API key"

  # GIVEN coordinator without ANTHROPIC_API_KEY
  log_step "GIVEN coordinator without API key"
  local fallback_task_id="fallback-test-$(date +%s)"
  local fallback_plan_file="/tmp/cfn-docker-plan-${fallback_task_id}.json"
  local fallback_container="cfn-coordinator-${fallback_task_id}"

  # WHEN task description provided
  log_step "WHEN task description provided without API key"
  local task_desc="Implement backend-developer task"

  # Start coordinator without API key (with 30 second timeout)
  timeout 35s docker run --rm \
    --name "$fallback_container" \
    --network mcp-network \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v "$(pwd):/app/codebase:ro" \
    -v /tmp:/tmp \
    -e "TASK_ID=${fallback_task_id}" \
    -e "TASK_DESCRIPTION=${task_desc}" \
    -e "MODE=mvp" \
    -e "CFN_REDIS_HOST=cfn-redis" \
    -e "CFN_REDIS_PORT=6379" \
    -e "MAX_ITERATIONS=1" \
    "$COORDINATOR_IMAGE" > /tmp/coordinator-fallback-output.log 2>&1 || true

  # THEN coordinator falls back to keyword matching
  log_step "THEN coordinator uses keyword matching fallback"
  if grep -q "Waiting 30 seconds for external plan file" /tmp/coordinator-fallback-output.log || \
     grep -q "keyword matching" /tmp/coordinator-fallback-output.log || \
     grep -q "backend-developer" /tmp/coordinator-fallback-output.log; then
    log_success "Coordinator used fallback mechanism"
  else
    log_error "No evidence of fallback mechanism"
    log_info "Output:"
    cat /tmp/coordinator-fallback-output.log | head -30
    return 1
  fi

  # Cleanup fallback artifacts
  docker rm -f "$fallback_container" 2>/dev/null || true
  rm -f "$fallback_plan_file" 2>/dev/null || true

  log_success "✅ Test 4 PASSED: Coordinator falls back without API key"
}

# Execute tests
log_section "Coordinator V3 - Dynamic Planning Tests (P0)"
log_info "Testing coordinator planning phase with Anthropic API"
echo ""

test_planning_phase_calls_api
test_plan_file_has_atomic_tasks
test_atomic_tasks_within_time_bounds
test_fallback_without_api_key

log_section "All Planning Tests Complete"
log_success "4/4 tests executed"
