#!/usr/bin/env bash
# tests/test-wiki-generate.sh - cfn-wiki Phase 3 harness.
# Covers: lib/import-existing.sh (enrich-import: hand-written fixture rows
# reappear as enrich blocks, unmatched rows orphaned, run is idempotent and a
# GENERATED marker makes it a no-op), lib/merge-enrichment.sh +
# lib/gen-projections.sh (enrich-preserve: edited block survives a same-fp
# regen, stale block replaced and re-attached from blocks/; projections-lint:
# generated fixture projections pass the real cfn-doc-lint), lib/gen-pages.sh
# (pages-shape: every fid gets a page with Source grounding, features_dir
# config honored), lib/lint-pages.sh (lint-catches: seeded bad page fails,
# good page passes, zero-page dir says so). Plan: fuzzy-whistling-eich Phase 3.
# Isolation: every case runs in temp dirs; the shipped fixture is only written
# by projections-lint (extract + generate into it, gitignored store aside),
# which is the plan's verify command. Hand-written fixture docs are restored
# from heredocs below so case order never matters.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LIB="$ROOT/.claude/skills/cfn-wiki/lib"
FIXTURE="$ROOT/tests/fixtures/wiki-fixture-repo"
DOCLINT="$ROOT/.claude/skills/cfn-doc-lint/execute.sh"

T="$(mktemp -d "${TMPDIR:-/tmp}/wiki-generate-test-XXXXXX")"
cleanup() { rm -rf "$T"; }
trap cleanup EXIT

PASS=0; FAIL=0; SKIP=0
ok()   { echo "PASS: $1"; PASS=$((PASS+1)); }
no()   { echo "FAIL: $1"; FAIL=$((FAIL+1)); }
skip() { echo "SKIP: $1"; SKIP=$((SKIP+1)); }

for dep in bash python3 git mktemp; do
    command -v "$dep" >/dev/null 2>&1 || { echo "FATAL: $dep not on PATH"; exit 1; }
done
[ -f "$DOCLINT" ] || { echo "FATAL: cfn-doc-lint execute.sh missing at $DOCLINT"; exit 1; }

# Run a lib function in a clean subshell: run_in <lib.sh> <fn> [args...]
run_in() {
    bash -c '
        set -uo pipefail
        source "$1"
        shift
        "$@"
    ' _ "$@"
}

# Evaluate a python expression over a store.json: store_val <file> <expr>
store_val() {
    python3 -c '
import json, sys
with open(sys.argv[1], encoding="utf-8") as fh:
    s = json.load(fh)
print(eval(sys.argv[2]))
' "$1" "$2"
}

store_fids() { # <store> -> newline-separated fids
    python3 -c '
import json, sys
with open(sys.argv[1], encoding="utf-8") as fh:
    s = json.load(fh)
print("\n".join(f["fid"] for f in s.get("features", [])))
' "$1"
}

# The pristine hand-written docs (pre-wiki state of the fixture readme).
write_handwritten_readme() { # <dest-repo>
    mkdir -p "$1/readme"
    cat >"$1/readme/feature-status.md" <<'EOF'
# Fixture Repo — Feature Status

**Last Updated:** 2026-09-12 (fixture placeholder; regenerated by `wiki sync`)

Status Legend: `prod | beta | dev | stub | deprecated`

| Feature | Status | Description | Dependencies | Known Limitations |
|---------|--------|-------------|--------------|-------------------|
| parsing | dev | Tokenizes raw `name,value` lines into structured records (fixture sample). | util | Placeholder row; replaced by `wiki sync` generation. |
| reporting | dev | Renders parsed records as text tables and TS count summaries (fixture sample). | parsing | Placeholder row; replaced by `wiki sync` generation. |
EOF
    cat >"$1/readme/state-machines.md" <<'EOF'
# Fixture Repo — State Machines

**Source:** placeholder — regenerated by `wiki sync` from `.wiki/store.json`

## Report

**Source:** service.py `build_report` (fixture placeholder)

### States

| State | Meaning |
|-------|---------|
| empty | No parsed records yet |
| built | Report rendered from parsed records |

### Transitions

| From | To | Trigger | Guard |
|------|----|---------|-------|
| empty | built | `build_report` called with >=1 line | none |
EOF
}

# Fixture copy with no .wiki and the pristine hand-written readme.
make_repo() { # <dest>
    local dest="$1"
    mkdir -p "$dest"
    cp -r "$FIXTURE/." "$dest/"
    rm -rf "$dest/.wiki" "$dest/readme"
    write_handwritten_readme "$dest"
}

blocks_dir() { printf '%s/.wiki/enrich/blocks' "$1"; }
blocks_sum() { cat "$1"/.wiki/enrich/blocks/*.md 2>/dev/null | sha256sum | cut -d" " -f1; }

# Insert a marker line inside the id=parsing enrich block of a generated file.
edit_parsing_block() { # <feature-status.md>
    python3 - "$1" <<'PY'
import sys
path = sys.argv[1]
with open(path, encoding="utf-8") as fh:
    text = fh.read()
start = text.index("<!-- wiki:enrich id=parsing fp=")
end = text.index("<!-- /wiki:enrich -->", start)
text = text[:end] + "EDITED-MARKER-42\n" + text[end:]
with open(path, "w", encoding="utf-8") as fh:
    fh.write(text)
PY
}

# ---------------------------------------------------------------------------
case_enrich_import() {
    if [ ! -f "$LIB/import-existing.sh" ]; then no "enrich-import: lib/import-existing.sh exists"; return; fi
    ok "enrich-import: lib/import-existing.sh exists"

    local REPO="$T/import"
    make_repo "$REPO"
    run_in "$LIB/extract-features.sh" wiki_extract "$REPO" >/dev/null 2>&1 \
        && ok "enrich-import: extract on temp copy" \
        || { no "enrich-import: extract failed"; return; }
    local STORE="$REPO/.wiki/store.json"
    store_fids "$STORE" | grep -q parsing \
        && ok "enrich-import: store has parsing fid" \
        || no "enrich-import: store lacks parsing fid"

    if run_in "$LIB/import-existing.sh" wiki_import_existing "$REPO" >"$T/import.log" 2>&1; then
        ok "enrich-import: wiki_import_existing exit 0"
    else
        no "enrich-import: import failed: $(tail -3 "$T/import.log")"
        return
    fi

    local B; B="$(blocks_dir "$REPO")"
    [ -f "$B/parsing.md" ] && grep -q "Tokenizes raw" "$B/parsing.md" \
        && ok "enrich-import: parsing row carried into blocks/parsing.md" \
        || no "enrich-import: parsing block missing or wrong content"
    [ -f "$B/reporting.md" ] && grep -q "Renders parsed records" "$B/reporting.md" \
        && ok "enrich-import: reporting row carried into blocks/reporting.md" \
        || no "enrich-import: reporting block missing or wrong content"
    grep -q "imported from readme/feature-status.md" "$B/parsing.md" \
        && ok "enrich-import: block records provenance" \
        || no "enrich-import: block lacks provenance marker"

    [ -f "$REPO/.wiki/enrich/orphans.md" ] && grep -q "Report" "$REPO/.wiki/enrich/orphans.md" \
        && ok "enrich-import: unmatched Report entity recorded in orphans.md" \
        || no "enrich-import: Report entity not orphaned"
    [ ! -f "$B/entity-report.md" ] \
        && ok "enrich-import: unmatched entity not written as a block" \
        || no "enrich-import: entity-report.md written despite no fid match"

    # idempotent without a marker: second run rewrites identical bytes
    local sum1 sum2
    sum1="$(blocks_sum "$REPO")"
    run_in "$LIB/import-existing.sh" wiki_import_existing "$REPO" >/dev/null 2>&1 || true
    sum2="$(blocks_sum "$REPO")"
    [ -n "$sum1" ] && [ "$sum1" = "$sum2" ] \
        && ok "enrich-import: rerun without marker rewrites identical blocks" \
        || no "enrich-import: rerun changed blocks ($sum1 vs $sum2)"
    [ "$(grep -c "^## Report" "$REPO/.wiki/enrich/orphans.md")" -eq 1 ] \
        && ok "enrich-import: orphans.md rewritten, not appended" \
        || no "enrich-import: orphans.md duplicated Report entries"

    # marker no-op: generated projections carry the marker, import skips
    run_in "$LIB/gen-projections.sh" wiki_gen_projections "$STORE" "$REPO" >/dev/null 2>&1 \
        && ok "enrich-import: gen-projections wrote marker" \
        || { no "enrich-import: gen-projections failed"; return; }
    grep -q "GENERATED by cfn-wiki" "$REPO/readme/feature-status.md" \
        && ok "enrich-import: GENERATED marker present" \
        || no "enrich-import: GENERATED marker missing"
    local sum3
    sum3="$(blocks_sum "$REPO")"
    run_in "$LIB/import-existing.sh" wiki_import_existing "$REPO" >/dev/null 2>&1 || true
    [ "$sum3" = "$(blocks_sum "$REPO")" ] \
        && ok "enrich-import: rerun with GENERATED marker is a no-op" \
        || no "enrich-import: marker run still rewrote blocks"
}

# ---------------------------------------------------------------------------
case_enrich_preserve() {
    if [ ! -f "$LIB/merge-enrichment.sh" ]; then no "enrich-preserve: lib/merge-enrichment.sh exists"; return; fi
    ok "enrich-preserve: lib/merge-enrichment.sh exists"
    if [ ! -f "$LIB/gen-projections.sh" ]; then no "enrich-preserve: lib/gen-projections.sh exists"; return; fi
    ok "enrich-preserve: lib/gen-projections.sh exists"

    local REPO="$T/preserve"
    make_repo "$REPO"
    run_in "$LIB/extract-features.sh" wiki_extract "$REPO" >/dev/null 2>&1 || { no "enrich-preserve: extract failed"; return; }
    local STORE="$REPO/.wiki/store.json"
    run_in "$LIB/import-existing.sh" wiki_import_existing "$REPO" >/dev/null 2>&1 || true
    local FS="$REPO/readme/feature-status.md"

    run_in "$LIB/gen-projections.sh" wiki_gen_projections "$STORE" "$REPO" >/dev/null 2>&1 \
        && ok "enrich-preserve: first generation" \
        || { no "enrich-preserve: first generation failed"; return; }
    grep -q "wiki:enrich id=parsing fp=" "$FS" \
        && ok "enrich-preserve: block carries id and fp attributes" \
        || { no "enrich-preserve: no id/fp block in feature-status.md"; return; }
    grep -q "Tokenizes raw" "$FS" \
        && ok "enrich-preserve: imported text embedded on first gen" \
        || no "enrich-preserve: imported text absent on first gen"

    # simulate Claude editing the enrich block in the generated md
    edit_parsing_block "$FS"
    run_in "$LIB/gen-projections.sh" wiki_gen_projections "$STORE" "$REPO" >/dev/null 2>&1 || { no "enrich-preserve: second gen failed"; return; }
    grep -q "EDITED-MARKER-42" "$FS" \
        && ok "enrich-preserve: edited block survives same-fp regen" \
        || no "enrich-preserve: edited block dropped by same-fp regen"

    # stale the feature: its file list changes, so the feature fp moves
    python3 - "$STORE" <<'PY'
import json, sys
path = sys.argv[1]
with open(path, encoding="utf-8") as fh:
    store = json.load(fh)
for f in store["features"]:
    if f["fid"] == "parsing":
        f["files"] = sorted(set(f["files"]) | {"parsing/extra.py"})
with open(path, "w", encoding="utf-8") as fh:
    json.dump(store, fh, indent=2)
    fh.write("\n")
PY
    run_in "$LIB/gen-projections.sh" wiki_gen_projections "$STORE" "$REPO" >/dev/null 2>&1 || { no "enrich-preserve: stale gen failed"; return; }
    if grep -q "EDITED-MARKER-42" "$FS"; then
        no "enrich-preserve: stale block not replaced (edit survived fp change)"
    else
        ok "enrich-preserve: stale block replaced after feature fp change"
    fi
    grep -q "Tokenizes raw" "$FS" \
        && ok "enrich-preserve: stale regen re-attaches text from blocks/" \
        || no "enrich-preserve: stale regen lost the blocks/ enrichment text"
}

# ---------------------------------------------------------------------------
case_projections_lint() {
    if [ ! -f "$LIB/gen-projections.sh" ]; then no "projections-lint: lib/gen-projections.sh exists"; return; fi
    ok "projections-lint: lib/gen-projections.sh exists"

    # the plan's verify command: generate the shipped fixture projections in
    # place, then run the real linter over the fixture repo. Extraction runs
    # on a plain temp copy and its store is installed into the fixture: the
    # fixture is a non-repo dir inside THIS repo, so a direct extract would
    # walk the whole 1455-commit outer history in extract's O(k^2) coupling
    # step (the cap its own cfn: comment anticipates). A no-git copy yields
    # the same degraded store for these file contents.
    local TMPSRC="$T/proj-src"
    mkdir -p "$TMPSRC"
    cp -r "$FIXTURE/." "$TMPSRC/"
    rm -rf "$TMPSRC/.wiki"
    run_in "$LIB/extract-features.sh" wiki_extract "$TMPSRC" >/dev/null 2>&1 \
        && ok "projections-lint: extract on fixture content copy" \
        || { no "projections-lint: extract on fixture copy failed"; return; }
    mkdir -p "$FIXTURE/.wiki"
    cp "$TMPSRC/.wiki/store.json" "$FIXTURE/.wiki/store.json" \
        && ok "projections-lint: store installed into fixture" \
        || { no "projections-lint: store install failed"; return; }
    local STORE="$FIXTURE/.wiki/store.json"
    run_in "$LIB/import-existing.sh" wiki_import_existing "$FIXTURE" >/dev/null 2>&1 || true
    run_in "$LIB/gen-projections.sh" wiki_gen_projections "$STORE" "$FIXTURE" >/dev/null 2>&1 \
        && ok "projections-lint: generate fixture projections" \
        || { no "projections-lint: generate failed"; return; }

    local FS="$FIXTURE/readme/feature-status.md" SM="$FIXTURE/readme/state-machines.md"
    local head_fs head_sm
    head_fs="$(head -2 "$FS")"; head_sm="$(head -2 "$SM")"
    printf '%s\n%s\n' "$head_fs" "$head_sm" | grep -q "GENERATED by cfn-wiki sync. DO NOT EDIT." \
        && ok "projections-lint: GENERATED header is line 1 of both projections" \
        || no "projections-lint: GENERATED header misplaced"
    printf '%s\n%s\n' "$head_fs" "$head_sm" | grep -Eq "wiki-fp: [0-9a-f]{64}" \
        && ok "projections-lint: wiki-fp line 2 of both projections" \
        || no "projections-lint: wiki-fp line missing or malformed"

    grep -q '^| Feature | Status | Description | Dependencies | Known Limitations |$' "$FS" \
        && ok "projections-lint: exact required columns in feature-status.md" \
        || no "projections-lint: feature-status.md column row wrong"
    for tok in prod beta dev stub deprecated; do
        grep -qw "$tok" "$FS" || no "projections-lint: status token $tok absent from feature-status.md"
    done
    ok "projections-lint: all five status tokens present (legend)"

    grep -q '```mermaid' "$SM" \
        && ok "projections-lint: mermaid fences kept in state-machines.md" \
        || no "projections-lint: state-machines.md lost mermaid fences"
    local n_entities n_src
    n_entities="$(grep -c '^## ' "$SM" || true)"
    n_src="$(grep -c '\*\*Source:\*\*' "$SM" || true)"
    [ "$n_entities" -ge 2 ] && [ "$n_src" -ge "$n_entities" ] \
        && ok "projections-lint: every entity carries Source grounding ($n_entities entities)" \
        || no "projections-lint: entity/Source counts wrong (entities=$n_entities src=$n_src)"
    local fids entities_ok=1 fid
    while IFS= read -r fid; do
        [ -n "$fid" ] || continue
        grep -Eq "^## [0-9]+\. $fid$" "$SM" || entities_ok=0
    done <<EOF
$(store_fids "$STORE")
EOF
    [ "$entities_ok" -eq 1 ] \
        && ok "projections-lint: one numbered H2 entity per store fid" \
        || no "projections-lint: a store fid has no state-machines entity"

    if bash "$DOCLINT" "$FIXTURE" >"$T/doclint.log" 2>&1; then
        ok "projections-lint: cfn-doc-lint exit 0 on generated fixture projections"
    else
        no "projections-lint: cfn-doc-lint failed: $(tail -5 "$T/doclint.log")"
    fi
}

# ---------------------------------------------------------------------------
case_pages_shape() {
    if [ ! -f "$LIB/gen-pages.sh" ]; then no "pages-shape: lib/gen-pages.sh exists"; return; fi
    ok "pages-shape: lib/gen-pages.sh exists"
    if [ ! -f "$LIB/lint-pages.sh" ]; then no "pages-shape: lib/lint-pages.sh exists"; return; fi
    ok "pages-shape: lib/lint-pages.sh exists"

    local REPO="$T/pages"
    make_repo "$REPO"
    run_in "$LIB/extract-features.sh" wiki_extract "$REPO" >/dev/null 2>&1 || { no "pages-shape: extract failed"; return; }
    local STORE="$REPO/.wiki/store.json"
    run_in "$LIB/import-existing.sh" wiki_import_existing "$REPO" >/dev/null 2>&1 || true
    run_in "$LIB/gen-projections.sh" wiki_gen_projections "$STORE" "$REPO" >/dev/null 2>&1 || true
    run_in "$LIB/gen-pages.sh" wiki_gen_pages "$STORE" "$REPO" >/dev/null 2>&1 \
        && ok "pages-shape: wiki_gen_pages exit 0" \
        || { no "pages-shape: gen pages failed"; return; }

    local fid page bad=0
    while IFS= read -r fid; do
        [ -n "$fid" ] || continue
        page="$REPO/readme/wiki/$fid/wiki.md"
        if [ ! -f "$page" ]; then no "pages-shape: missing page for $fid"; bad=1; continue; fi
        grep -q '\*\*Source:\*\*' "$page" || { no "pages-shape: $fid page lacks Source grounding"; bad=1; }
        grep -q '^\*\*Status:\*\* dev$' "$page" || { no "pages-shape: $fid page lacks status line"; bad=1; }
        grep -q '<!-- /wiki:enrich -->' "$page" || { no "pages-shape: $fid page lacks enrich block"; bad=1; }
    done <<EOF
$(store_fids "$STORE")
EOF
    [ "$bad" -eq 0 ] && ok "pages-shape: every fid has a page with Source, status, enrich block"

    # features_dir override via .wiki/config.json
    printf '{"features_dir": "docs/wik"}\n' >"$REPO/.wiki/config.json"
    run_in "$LIB/gen-pages.sh" wiki_gen_pages "$STORE" "$REPO" >/dev/null 2>&1 || { no "pages-shape: config regen failed"; return; }
    [ -f "$REPO/docs/wik/parsing/wiki.md" ] \
        && ok "pages-shape: features_dir config override honored (docs/wik/)" \
        || no "pages-shape: config override ignored (no docs/wik/parsing/wiki.md)"

    if run_in "$LIB/lint-pages.sh" wiki_lint "$REPO" >"$T/lint-repo.log" 2>&1; then
        ok "pages-shape: wiki_lint passes on generated pages"
    else
        no "pages-shape: wiki_lint failed on generated pages: $(tail -3 "$T/lint-repo.log")"
    fi
}

# ---------------------------------------------------------------------------
case_lint_catches() {
    local D="$T/lint"
    mkdir -p "$D/good" "$D/bad" "$D/empty"
    cat >"$D/good/wiki.md" <<'EOF'
# good

**Source:**

- `src/a.py`

**Status:** dev

<!-- wiki:enrich id=good fp=abc -->
note
<!-- /wiki:enrich -->
EOF
    cat >"$D/bad/wiki.md" <<'EOF'
# bad

**Status:** shipped

No grounding, no enrich block here.
EOF

    if run_in "$LIB/lint-pages.sh" wiki_lint "$D/good" >"$T/lint-good.log" 2>&1; then
        ok "lint-catches: good page passes"
    else
        no "lint-catches: good page rejected: $(tail -3 "$T/lint-good.log")"
    fi

    local rc=0
    run_in "$LIB/lint-pages.sh" wiki_lint "$D" >"$T/lint-bad.log" 2>&1 || rc=$?
    if [ "$rc" -eq 1 ]; then
        ok "lint-catches: seeded bad page fails with exit 1"
    else
        no "lint-catches: bad page exit=$rc (want 1)"
    fi
    grep -q "bad/wiki.md" "$T/lint-bad.log" \
        && ok "lint-catches: finding names the offending file" \
        || no "lint-catches: finding does not name bad/wiki.md"
    grep -q "Source" "$T/lint-bad.log" \
        && ok "lint-catches: missing Source grounding reported" \
        || no "lint-catches: Source check silent"
    grep -q "shipped" "$T/lint-bad.log" \
        && ok "lint-catches: bad status token reported" \
        || no "lint-catches: status token check silent"

    if run_in "$LIB/lint-pages.sh" wiki_lint "$D/empty" >"$T/lint-empty.log" 2>&1; then
        grep -q "0 wiki.md" "$T/lint-empty.log" \
            && ok "lint-catches: zero-page dir exits 0 and says it examined nothing" \
            || no "lint-catches: zero-page dir passed silently without a count"
    else
        no "lint-catches: zero-page dir should not fail"
    fi
}

# ---------------------------------------------------------------------------
case_enrich_import
case_enrich_preserve
case_projections_lint
case_pages_shape
case_lint_catches
skip "real-repo-lint: deferred to Phase 7 (first wiki sync on this repo; verify via cfn-doc-lint execute.sh readme)"

echo
echo "wiki-generate: $PASS passed, $FAIL failed, $SKIP skipped"
[ "$FAIL" -eq 0 ]
