#!/bin/bash

echo "=========================================="
echo "⚠️  DEPRECATED: orchestrate-cfn-loop.sh"
echo "=========================================="
echo ""
echo "This orchestrator has been replaced by the modular CFN v3 version."
echo ""
echo "New Location:"
echo "  ./.claude/skills/cfn-loop-orchestration/orchestrate.sh"
echo ""
echo "Key Improvements in v3:"
echo "  - 78% code reduction (70KB → 26KB)"
echo "  - Modular helper scripts"
echo "  - Stateless context injection"
echo "  - Better agent ID tracking"
echo "  - No BLPOP hangs"
echo ""
echo "Migration:"
echo "  Replace: orchestrate-cfn-loop.sh"
echo "  With:    cfn-loop-orchestration/orchestrate.sh"
echo ""
echo "Same parameters supported (backward compatible)"
echo ""
echo "=========================================="
echo ""
echo "Forwarding to new orchestrator..."
echo ""

# Forward to new version
exec "$(dirname "$0")/../cfn-loop-orchestration/orchestrate.sh" "$@"
