apiVersion: v1
kind: ConfigMap
metadata:
  name: cfn-coordination-config-prod
  namespace: claude-flow-novice
  labels:
    app: claude-flow-novice
    environment: production
    component: coordination
data:
  # Environment
  NODE_ENV: "production"

  # Agent Configuration (Production: 500 agents)
  CFN_MAX_AGENTS: "500"
  CFN_SHARD_COUNT: "32"
  CFN_METRICS_ENABLED: "true"
  CFN_ALERTING_ENABLED: "true"
  CFN_LOG_LEVEL: "warn"
  CFN_CONSENSUS_THRESHOLD: "0.95"
  CFN_ALERT_COORD_TIME_MS: "8000"

  # Memory and Storage (tmpfs REQUIRED)
  CFN_BASE_DIR: "/dev/shm/cfn"
  CFN_AGENT_MEMORY_LIMIT_MB: "100"
  CFN_TOTAL_MEMORY_LIMIT_MB: "51200"

  # Performance
  CFN_AGENT_TIMEOUT_MS: "30000"
  CFN_CONSENSUS_TIMEOUT_MS: "60000"
  CFN_SWARM_INIT_TIMEOUT_MS: "10000"
  CFN_ENABLE_CACHING: "true"
  CFN_CACHE_TTL_SECONDS: "600"
  CFN_MAX_CONCURRENT_OPERATIONS: "100"

  # Resource Cleanup
  CFN_CLEANUP_INTERVAL_MS: "60000"
  CFN_CLEANUP_STALE_AGENTS_ENABLED: "true"

  # Monitoring
  CFN_METRICS_COLLECTION_INTERVAL_MS: "5000"
  CFN_METRICS_RETENTION_HOURS: "168"
  CFN_TRACK_COORDINATION_TIME: "true"
  CFN_TRACK_MEMORY_USAGE: "true"
  CFN_TRACK_AGENT_LIFECYCLE: "true"

  # Alerting Thresholds
  CFN_ALERT_MEMORY_THRESHOLD_PERCENT: "80"
  CFN_ALERT_AGENT_FAILURE_COUNT: "3"
  CFN_ALERT_CONSENSUS_FAILURE_THRESHOLD: "0.70"

  # Security (Production: REQUIRED)
  CFN_ENABLE_AGENT_AUTH: "true"
  CFN_ENABLE_TLS: "true"
  CFN_TLS_CERT_PATH: "/etc/cfn/certs/cert.pem"
  CFN_TLS_KEY_PATH: "/etc/cfn/certs/key.pem"
  CFN_ENABLE_RATE_LIMITING: "true"
  CFN_RATE_LIMIT_REQUESTS_PER_MINUTE: "1000"

  # MCP Server
  CFN_MCP_SERVER_ENABLED: "true"
  CFN_MCP_SERVER_PORT: "3000"

  # Testing and Debugging (Production: DISABLED)
  CFN_TEST_MODE: "false"
  CFN_DEBUG_AGENT_SPAWN: "false"
  CFN_DEBUG_CONSENSUS: "false"
  CFN_DEBUG_MEMORY: "false"
  CFN_VERBOSE_LOGGING: "false"

  # Chaos Engineering (Production: DISABLED)
  CFN_CHAOS_ENABLED: "false"

  # Consensus Algorithm
  CFN_CONSENSUS_ALGORITHM: "byzantine"

  # Database (Production: PostgreSQL)
  CFN_DB_ENABLED: "true"
  CFN_DB_TYPE: "postgresql"
  CFN_DB_PORT: "5432"
  CFN_DB_NAME: "cfn_metrics"

  # Distributed Tracing
  CFN_TRACING_ENABLED: "true"
  CFN_TRACING_SERVICE_NAME: "claude-flow-novice"
