#!/usr/bin/env bash
# cfn-wiki per-feature page generator.
#
# Contract: wiki_gen_pages <store> <repo> -> one page per store feature at
# $features_dir/<fid>/wiki.md, exit 0. features_dir comes from
# .wiki/config.json key "features_dir" (default "readme/wiki"). Pages carry:
# Source grounding (the feature's file list), a closed-vocab Status line, a
# mermaid diagram of the feature's cross-module edges, the change-coupling
# pairs touching its files, and the enrichment block resolved by
# lib/merge-enrichment.sh (edited blocks survive while the feature fp holds).

# shellcheck disable=SC1091
[ -n "${WIKI_MERGE_ENRICH_LOADED:-}" ] \
    || source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/merge-enrichment.sh"

wiki_config_features_dir() { # <repo> -> features_dir value
    local repo="$1" cfg="$repo/.wiki/config.json" configured=""
    if [ -f "$cfg" ]; then
        configured="$(sed -n 's/.*"features_dir"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$cfg" 2>/dev/null | head -1)"
    fi
    printf '%s' "${configured:-readme/wiki}"
}

wiki_gen_pages() {
    local store="${1:?wiki_gen_pages: store path required}"
    local repo="${2:?wiki_gen_pages: repo path required}"
    if [ ! -f "$store" ]; then
        echo "wiki_gen_pages: no store at $store (run wiki_extract first)" >&2
        return 1
    fi
    repo="$(cd "$repo" && pwd)"

    local features_dir pages_root fid page
    features_dir="$(wiki_config_features_dir "$repo")"
    pages_root="$repo/$features_dir"

    # resolve against the projections first, then let previously generated
    # pages refresh the extract dir so page edits win for their own regen
    wiki_merge_enrich "$store" "$repo/readme"
    local extract_dir
    extract_dir="$(wiki_enrich_dir "$store")/extract"
    while IFS= read -r fid; do
        [ -n "$fid" ] || continue
        page="$pages_root/$fid/wiki.md"
        if [ -f "$page" ]; then
            wiki_enrich_extract "$page" "$extract_dir" >/dev/null
        fi
    done <<EOF
$(wiki_store_fids "$store")
EOF
    wiki_enrich_resolve "$store"

    mkdir -p "$pages_root"

    python3 - "$store" "$pages_root" <<'PY'
import json
import os
import re
import sys

store_path, pages_root = sys.argv[1], sys.argv[2]
with open(store_path, encoding="utf-8") as fh:
    store = json.load(fh)

features = store.get("features", [])
edges = store.get("edges", [])
coupling = store.get("coupling", [])
resolved = os.path.join(os.path.dirname(os.path.abspath(store_path)),
                        "enrich", "resolved")
store_fp = store.get("meta", {}).get("fingerprint", "")


def slug(text):
    # keep in sync with lib/extract-features.sh slug()
    s = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return s or "feature"


def esc(cell):
    return re.sub(r"\s+", " ", str(cell)).replace("|", "\\|").strip()


def enrich_block(block_id):
    with open(os.path.join(resolved, block_id + ".md"), encoding="utf-8") as fh:
        body = fh.read().strip("\n")
    with open(os.path.join(resolved, block_id + ".fp"), encoding="utf-8") as fh:
        fp = fh.read().strip()
    return "<!-- wiki:enrich id=%s fp=%s -->\n%s\n<!-- /wiki:enrich -->" \
        % (block_id, fp, body)


count = 0
for f in features:
    name = f["name"]
    files = f.get("files", [])

    page = ["<!-- GENERATED by cfn-wiki sync. DO NOT EDIT. -->",
            "<!-- wiki-fp: %s -->" % store_fp,
            "",
            "# %s" % name,
            "",
            "**Source:**",
            ""]
    page += ["- `%s`" % p for p in files] or ["- (no files recorded)"]
    page += ["", "**Status:** dev", ""]

    related = [e for e in edges
               if e.get("source") == name or e.get("target") == name]
    page += ["## Feature Edges", ""]
    if related:
        page += ["```mermaid", "flowchart LR"]
        for e in related:
            page.append('    %s["%s"] --> %s["%s"]'
                        % (slug(e["source"]), e["source"],
                           slug(e["target"]), e["target"]))
        page += ["```", ""]
    else:
        page += ["No cross-module edges recorded (degraded index).", ""]

    pairs = [p for p in coupling
             if p["files"][0] in files or p["files"][1] in files]
    page += ["## Change Coupling", ""]
    if pairs:
        page += ["| Files | Commits |", "|-------|---------|"]
        for p in pairs:
            page.append("| `%s`, `%s` | %d |" % (p["files"][0], p["files"][1],
                                                 p["count"]))
        page.append("")
    else:
        page += ["No co-change pairs recorded for these files.", ""]

    page += [enrich_block(f["fid"]), ""]

    out_path = os.path.join(pages_root, f["fid"], "wiki.md")
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    tmp = out_path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write("\n".join(page))
    os.replace(tmp, out_path)
    count += 1

print("wiki: generated %d feature pages under %s" % (count, pages_root))
PY
}
