#!/usr/bin/env bash
# cfn-wiki projection generator: write <repo>/readme/feature-status.md and
# <repo>/readme/state-machines.md from the deterministic store.
#
# Contract: wiki_gen_projections <store> <repo> -> exit 0, both files written
# atomically (tmp + rename). Output must pass cfn-doc-lint (see
# .claude/skills/cfn-doc-lint/SCHEMA.md):
#   - line 1 GENERATED marker, line 2 wiki-fp (whole-store fingerprint, the
#     drift-gate key for `wiki sync --check`)
#   - **Last Updated:** date stamp within the first 20 lines
#   - Status Legend + exact required columns; status tokens come from the
#     closed enum prod|beta|dev|stub|deprecated
#   - table cells stay far under the 280-char aim
#   - >300-line files get the rollup table (feature-status) or anchor-link TOC
#     (state-machines) at the top
#   - state machines: one numbered H2 per feature, **Source:** grounding,
#     ### States, ### Transitions (From|To|Trigger|Guard), exactly one diagram
#     style (mermaid fences, kept as fences for GitHub rendering)
#   - enrichment embedded as wiki:enrich blocks resolved by lib/merge-enrichment.sh
#
# cfn: Status is fixed to dev for every auto-extracted feature; per-feature
# statuses arrive when enrich-block status keys land (Phase 5 view-catalog).

# shellcheck disable=SC1091
[ -n "${WIKI_MERGE_ENRICH_LOADED:-}" ] \
    || source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/merge-enrichment.sh"

wiki_gen_projections() {
    local store="${1:?wiki_gen_projections: store path required}"
    local repo="${2:?wiki_gen_projections: repo path required}"
    if [ ! -f "$store" ]; then
        echo "wiki_gen_projections: no store at $store (run wiki_extract first)" >&2
        return 1
    fi
    repo="$(cd "$repo" && pwd)"
    mkdir -p "$repo/readme"

    # resolve enrichment against the previously generated projections
    wiki_merge_enrich "$store" "$repo/readme"

    local today
    today="$(date +%Y-%m-%d)"

    python3 - "$store" "$repo" "$today" <<'PY'
import glob
import hashlib
import json
import os
import re
import sys

store_path, repo, today = sys.argv[1], sys.argv[2], sys.argv[3]
with open(store_path, encoding="utf-8") as fh:
    store = json.load(fh)

store_fp = store.get("meta", {}).get("fingerprint", "")
if not re.fullmatch(r"[0-9a-f]{64}", store_fp):
    sys.exit("wiki_gen_projections: store meta.fingerprint missing or malformed")

features = store.get("features", [])
edges = store.get("edges", [])
resolved = os.path.join(os.path.dirname(os.path.abspath(store_path)),
                        "enrich", "resolved")

STATUS_MEANINGS = [
    ("prod", "Live, verified, monitored. Real users."),
    ("beta", "Feature-complete, under verification."),
    ("dev", "In development. Not verifiable end-to-end."),
    ("stub", "Scaffold only. Returns placeholder."),
    ("deprecated", "Scheduled for removal. Do not build on."),
]
CURRENT_STATUS = "dev"


def slug(text):
    # keep in sync with lib/extract-features.sh slug()
    s = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return s or "feature"


def esc(cell):
    out = re.sub(r"\s+", " ", str(cell)).replace("|", "\\|").strip()
    return out or "-"


def enrich_block(block_id):
    path = os.path.join(resolved, block_id + ".md")
    fp_path = os.path.join(resolved, block_id + ".fp")
    if not (os.path.isfile(path) and os.path.isfile(fp_path)):
        sys.exit("wiki_gen_projections: unresolved enrich id %s "
                 "(wiki_merge_enrich must run first)" % block_id)
    with open(path, encoding="utf-8") as fh:
        body = fh.read().strip("\n")
    with open(fp_path, encoding="utf-8") as fh:
        fp = fh.read().strip()
    return "<!-- wiki:enrich id=%s fp=%s -->\n%s\n<!-- /wiki:enrich -->" \
        % (block_id, fp, body)


HEADER = [
    "<!-- GENERATED by cfn-wiki sync. DO NOT EDIT. -->",
    "<!-- wiki-fp: %s -->" % store_fp,
    "",
]


def appendix(kind):
    # zero-content-loss: hand-written rows that matched no store fid are
    # embedded verbatim so they survive regens and show up in git diffs for
    # triage. The H2 title starts with "Appendix" so the doc-lint entity
    # scanner treats it as front matter, not a state machine.
    items = sorted(glob.glob(os.path.join(resolved, "orphan-%s-*.md" % kind)))
    if not items:
        return []
    out = ["## Appendix. Imported notes (unmatched)", "",
           "Hand-written rows below matched no store feature fid. Kept",
           "verbatim for triage; resolve by renaming the row to the feature",
           "name and re-running the import.", ""]
    for path in items:
        block_id = os.path.basename(path)[:-3]
        out += [enrich_block(block_id), ""]
    return out

# ---- feature-status.md ------------------------------------------------------
lines = list(HEADER)
lines += ["# Feature Status", "",
          "**Last Updated:** %s wiki sync" % today, "",
          "## Status Legend", "",
          "| Status | Meaning |", "|--------|---------|"]
for tok, meaning in STATUS_MEANINGS:
    lines.append("| %s | %s |" % (tok, meaning))
lines.append("")

inbound = {}
for e in edges:
    inbound.setdefault(e.get("target", ""), set()).add(e.get("source", ""))

if features:
    lines += ["| Feature | Status | Description | Dependencies | Known Limitations |",
              "|---------|--------|-------------|--------------|-------------------|"]
    for f in features:
        deps = sorted(d for d in inbound.get(f["name"], ()) if d)
        desc = "Auto-extracted feature: %d source files" % len(f.get("files", []))
        weight = f.get("edges", 0)
        if weight:
            desc += "; %d inbound cross-module edge calls" % weight
        desc += "."
        lines.append("| %s | %s | %s | %s | %s |" % (
            esc(f["name"]), CURRENT_STATUS, esc(desc),
            esc(", ".join(deps)),
            "Auto-generated row; curate via the wiki:enrich block under Feature Notes."))
    lines += ["", "## Feature Notes", ""]
    for f in features:
        lines += ["### %s" % f["name"], "", enrich_block(f["fid"]), ""]
else:
    lines += ["No features extracted yet. Run `wiki sync` after indexing;",
              "this file regenerates deterministically from .wiki/store.json.", ""]

lines += appendix("feature")

if len(lines) > 300:
    counts = {tok: 0 for tok, _ in STATUS_MEANINGS}
    counts[CURRENT_STATUS] = len(features)
    rollup = ["## Status Rollup", "", "| Status | Features |", "|--------|----------|"]
    for tok, _ in STATUS_MEANINGS:
        rollup.append("| %s | %d |" % (tok, counts[tok]))
    rollup.append("")
    lines = lines[:7] + rollup + lines[7:]

fs_path = os.path.join(repo, "readme", "feature-status.md")
fs_lines_text = list(lines)
fs_lines = len(fs_lines_text)

# ---- state-machines.md ------------------------------------------------------
lines = list(HEADER)
lines += ["# State Machines", "",
          "**Last Updated:** %s wiki sync" % today, ""]

if not features:
    lines += ["No stateful surfaces extracted yet. Run `wiki sync` after indexing;",
              "this file regenerates deterministically from .wiki/store.json.", ""]

for i, f in enumerate(features, 1):
    files = f.get("files", [])
    source = "%s:1" % files[0] if files else ".wiki/store.json"
    lines += ["## %d. %s" % (i, f["name"]), "",
              "**Source:** %s (auto-grounded from .wiki/store.json)" % source, "",
              "Status lifecycle of this feature in the closed doc-contract vocabulary.", "",
              "### States", "",
              "| State | Meaning |", "|-------|---------|"]
    for tok, meaning in STATUS_MEANINGS:
        mark = " (current)" if tok == CURRENT_STATUS else ""
        lines.append("| %s | %s%s |" % (tok, meaning, mark))
    lines += ["", "### Transitions", "",
              "| From | To | Trigger | Guard |",
              "|------|----|---------|-------|",
              "| (new) | stub | Feature scaffold appears in the tree | none |",
              "| stub | dev | First working implementation lands | none |",
              "| dev | beta | Feature-complete, verification pending | verification suite exists |",
              "| beta | prod | Verified and monitored in real use | zero known blockers |",
              "| prod | deprecated | Replacement shipped or feature retired | removal scheduled |",
              "", "### Diagram", "", "```mermaid", "stateDiagram-v2",
              "  [*] --> %s" % CURRENT_STATUS,
              "  stub --> dev",
              "  dev --> beta",
              "  beta --> prod",
              "  prod --> deprecated",
              "```", "",
              enrich_block("entity-" + f["fid"]), ""]

lines += appendix("entity")

if len(lines) > 300:
    toc = ["## Table of Contents", ""]
    for i, f in enumerate(features, 1):
        toc.append("- [%d. %s](#%d-%s)" % (i, f["name"], i, slug(f["name"])))
    toc.append("")
    lines = lines[:7] + toc + lines[7:]

sm_path = os.path.join(repo, "readme", "state-machines.md")
sm_lines_text = list(lines)
sm_lines = len(sm_lines_text)

# ---- atomic write of both projections ---------------------------------------
for path, text in ((fs_path, "\n".join(fs_lines_text)),
                   (sm_path, "\n".join(sm_lines_text))):
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(text)
        fh.write("\n")
    os.replace(tmp, path)

print("wiki: generated %s (%d lines), %s (%d lines)"
      % (fs_path, fs_lines, sm_path, sm_lines))
PY
}
