#!/usr/bin/env bash
# cfn-wiki one-time carry-over: convert hand-written readme docs into enrich
# block sources.
#
# Contract: wiki_import_existing <repo> -> writes <repo>/.wiki/enrich/blocks/
# and .wiki/enrich/orphans.md, exit 0 (a no-op is still success).
#
#   - readme/feature-status.md table rows become blocks/<fid>.md, one per
#     feature row (description, dependencies, known limitations). fid = slug of
#     the feature name (same slug as lib/extract-features.sh).
#   - readme/state-machines.md entities become blocks/entity-<slug>.md with
#     the captured Source line, States section and Transitions section.
#   - Rows whose slug matches no store feature fid go to
#     .wiki/enrich/orphans.md instead (rewritten each run, never appended).
#
# Idempotency: a file carrying the GENERATED marker (written by
# lib/gen-projections.sh) is skipped, so a second run after the first sync is
# a no-op. Before any generation exists, a rerun rewrites the same block bytes
# (blocks are replaced, not appended), so repeated imports are also stable.
# After the marker exists, lib/merge-enrichment.sh owns these files and a
# re-import never clobbers Claude's edits.

wiki_import_existing() {
    local repo="${1:?wiki_import_existing: repo path required}"
    if [ ! -d "$repo" ]; then
        echo "wiki_import_existing: no such repo: $repo" >&2
        return 1
    fi
    repo="$(cd "$repo" && pwd)"

    python3 - "$repo" <<'PY'
import json
import os
import re
import sys

repo = sys.argv[1]
readme = os.path.join(repo, "readme")
enrich = os.path.join(repo, ".wiki", "enrich")
blocks_dir = os.path.join(enrich, "blocks")
orphans_path = os.path.join(enrich, "orphans.md")
GENERATED = "GENERATED by cfn-wiki"


def slug(text):
    # keep in sync with lib/extract-features.sh slug()
    s = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return s or "feature"


def read(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def cells(line):
    parts = line.strip().split("|")
    if parts and parts[0].strip() == "":
        parts = parts[1:]
    if parts and parts[-1].strip() == "":
        parts = parts[:-1]
    return [p.strip() for p in parts]


def is_separator(cs):
    return bool(cs) and all(re.fullmatch(r":?-{2,}:?", c) for c in cs)


# store fids decide matched vs orphan; no store means nothing can match yet,
# so every row lands in blocks under its slug (matching happens post-extract).
store_fids = []
store_path = os.path.join(repo, ".wiki", "store.json")
if os.path.isfile(store_path):
    try:
        with open(store_path, encoding="utf-8") as fh:
            store_fids = [f.get("fid", "") for f in json.load(fh).get("features", [])]
    except ValueError:
        store_fids = []

feature_bodies = {}   # fid -> [section text]
entity_bodies = {}    # slug -> [section text]
orphans = []          # (kind, name, origin, body)
n_features = 0
n_entities = 0

fs_path = os.path.join(readme, "feature-status.md")
if os.path.isfile(fs_path):
    text = read(fs_path)
    if GENERATED in text:
        print("wiki: import skipped readme/feature-status.md (GENERATED marker)")
    else:
        lines = text.splitlines()
        hdr_i, cols = None, []
        for i, ln in enumerate(lines):
            if ln.lstrip().startswith("|"):
                cs = cells(ln)
                low = [c.lower() for c in cs]
                if "feature" in low and "status" in low:
                    hdr_i, cols = i, low
                    break
        if hdr_i is None:
            print("wiki: import found no feature table in readme/feature-status.md")
        else:
            for ln in lines[hdr_i + 1:]:
                if not ln.lstrip().startswith("|"):
                    break
                cs = cells(ln)
                if is_separator(cs):
                    continue

                def col(name):
                    if name in cols:
                        idx = cols.index(name)
                        if idx < len(cs):
                            return cs[idx]
                    return ""

                name = col("feature")
                if not name:
                    continue
                fid = slug(name)
                body = ["<!-- imported from readme/feature-status.md -->"]
                desc = col("description")
                deps = col("dependencies")
                lim = col("known limitations")
                if desc:
                    body += ["", "**Description:** " + desc]
                if deps:
                    body += ["", "**Dependencies:** " + deps]
                if lim:
                    body += ["", "**Known limitations:** " + lim]
                section = "\n".join(body) + "\n"
                if store_fids and fid not in store_fids:
                    orphans.append(("feature row", name,
                                    "readme/feature-status.md", section))
                else:
                    feature_bodies.setdefault(fid, []).append(section)
                    n_features += 1

sm_path = os.path.join(readme, "state-machines.md")
if os.path.isfile(sm_path):
    text = read(sm_path)
    if GENERATED in text:
        print("wiki: import skipped readme/state-machines.md (GENERATED marker)")
    else:
        lines = text.splitlines()
        h2 = [i for i, ln in enumerate(lines) if re.match(r"^##\s", ln)]
        for k, i in enumerate(h2):
            end = h2[k + 1] if k + 1 < len(h2) else len(lines)
            name = re.sub(r"^##\s+", "", lines[i]).strip()
            if re.match(r"^(table of contents|contents|toc|overview|legend|status|appendix)",
                        name, re.I):
                continue
            seg = "\n".join(lines[i + 1:end])

            m_src = re.search(r"\*\*(?:Source|Table|Location|File):\*\*[^\n]*", seg)

            def section_of(title):
                m = re.search(r"^###\s+[^\n]*" + title + r"[^\n]*\n(.*?)(?=^###\s|\Z)",
                              seg, re.M | re.S | re.I)
                return m.group(1).strip() if m else ""

            states = section_of("State")
            trans = section_of("Transition")
            body = ["<!-- imported from readme/state-machines.md -->",
                    "", "**Imported entity:** " + name]
            if m_src:
                body += ["", m_src.group(0)]
            if states:
                body += ["", "### States", "", states]
            if trans:
                body += ["", "### Transitions", "", trans]
            section = "\n".join(body) + "\n"
            norm = slug(re.sub(r"^\d+\.?\s*", "", name))
            if store_fids and norm not in store_fids:
                orphans.append(("entity", name, "readme/state-machines.md", section))
            else:
                entity_bodies.setdefault(norm, []).append(section)
                n_entities += 1

os.makedirs(blocks_dir, exist_ok=True)


def write_blocks(mapping, prefix):
    for key, sections in mapping.items():
        path = os.path.join(blocks_dir, prefix + key + ".md")
        with open(path, "w", encoding="utf-8") as fh:
            fh.write("\n".join(sections))


write_blocks(feature_bodies, "")
write_blocks(entity_bodies, "entity-")

if orphans:
    out = ["# Unmatched wiki imports", "",
           "Hand-written doc rows that matched no feature fid in",
           ".wiki/store.json. Matched rows live in .wiki/enrich/blocks/.",
           "Safe to delete once reviewed; rewritten on every import.", ""]
    for kind, name, origin, body in orphans:
        out += ["## %s (%s, %s)" % (name, kind, origin), "", body.rstrip(), ""]
    with open(orphans_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))
elif os.path.isfile(orphans_path):
    os.remove(orphans_path)

print("wiki: imported %d feature rows, %d entities, %d orphans (blocks: %s)"
      % (n_features, n_entities, len(orphans), blocks_dir))
PY
}
