#!/usr/bin/env bash
# cfn-wiki one-time carry-over: convert hand-written readme docs into enrich
# block sources.
#
# Contract: wiki_import_existing <repo> -> writes <repo>/.wiki/enrich/blocks/
# and .wiki/enrich/orphans.md, exit 0 (a no-op is still success).
#
#   - readme/feature-status.md table rows become blocks/<fid>.md, one per
#     feature row (description, dependencies, known limitations). fid = slug of
#     the feature name (same slug as lib/extract-features.sh).
#   - readme/state-machines.md entities become blocks/entity-<slug>.md with
#     the captured Source line, States section and Transitions section.
#   - Rows whose slug matches no store feature fid go to
#     .wiki/enrich/orphans.md instead (rewritten each run, never appended).
#
# Idempotency: a file carrying the GENERATED marker (written by
# lib/gen-projections.sh) is skipped, so a second run after the first sync is
# a no-op. Before any generation exists, a rerun rewrites the same block bytes
# (blocks are replaced, not appended), so repeated imports are also stable.
# After the marker exists, lib/merge-enrichment.sh owns these files and a
# re-import never clobbers Claude's edits.

wiki_import_existing() {
    local repo="${1:?wiki_import_existing: repo path required}"
    if [ ! -d "$repo" ]; then
        echo "wiki_import_existing: no such repo: $repo" >&2
        return 1
    fi
    repo="$(cd "$repo" && pwd)"

    python3 - "$repo" <<'PY'
import glob
import json
import os
import re
import sys

repo = sys.argv[1]
readme = os.path.join(repo, "readme")
enrich = os.path.join(repo, ".wiki", "enrich")
blocks_dir = os.path.join(enrich, "blocks")
orphans_path = os.path.join(enrich, "orphans.md")
GENERATED = "GENERATED by cfn-wiki"


def slug(text):
    # keep in sync with lib/extract-features.sh slug()
    s = re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")
    return s or "feature"


def read(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def cells(line):
    parts = line.strip().split("|")
    if parts and parts[0].strip() == "":
        parts = parts[1:]
    if parts and parts[-1].strip() == "":
        parts = parts[:-1]
    return [p.strip() for p in parts]


def is_separator(cs):
    return bool(cs) and all(re.fullmatch(r":?-{2,}:?", c) for c in cs)


# store features decide matched vs orphan. Matching ladder (first hit wins,
# per level logged to stderr):
#   a  exact slug equality
#   b  slug equality after stripping common product prefixes (cfn-, cfn-v)
#   c  token containment: all len>=3 tokens of one slug appear in the other
#      (highest overlap wins, lexicographic fid breaks ties)
#   d  path containment: the hand name's tokens appear in the fid's file list
# No store at all means nothing can match yet; rows land in blocks under
# their plain slug (level "slug") so a pre-extract import loses nothing.
store_feats = []
have_store = False
store_path = os.path.join(repo, ".wiki", "store.json")
if os.path.isfile(store_path):
    try:
        with open(store_path, encoding="utf-8") as fh:
            store_feats = [{"fid": f.get("fid", ""),
                            "files": f.get("files", [])}
                           for f in json.load(fh).get("features", [])]
        have_store = True
    except ValueError:
        store_feats = []
        have_store = False

PREFIXES = ("cfn-v", "cfn-")


def strip_prefixes(text):
    changed = True
    while changed:
        changed = False
        for p in PREFIXES:
            if text.startswith(p) and len(text) > len(p):
                text = text[len(p):]
                changed = True
    return text


def tokens_of(slug_text):
    return [t for t in slug_text.split("-") if len(t) >= 3]


level_counts = {}


def match_feature(name, fid):
    """Return (store_fid | None, level). Deterministic over store order."""
    if not have_store:
        return fid, "slug"
    if fid in [f["fid"] for f in store_feats]:
        return fid, "a"
    stripped = slug(strip_prefixes(name))
    if stripped in [f["fid"] for f in store_feats]:
        return stripped, "b"
    hand_toks = tokens_of(stripped)
    best = None
    best_inter = -1
    for f in store_feats:
        stoks = tokens_of(f["fid"])
        if not hand_toks or not stoks:
            continue
        inter = len(set(hand_toks) & set(stoks))
        if inter and (set(hand_toks) <= set(stoks) or set(stoks) <= set(hand_toks)) \
                and inter > best_inter:
            best, best_inter = f["fid"], inter
    if best:
        return best, "c"
    # Level d (file-list token containment) removed: on real data it attached
    # rows to the wrong modules ('GOAP Planner' -> src). Weak matches are
    # worse than orphans; unmatched rows land in the appendix.
    return None, None

feature_bodies = {}   # fid -> [section text]
entity_bodies = {}    # slug -> [section text]
orphans = []          # (kind, name, origin, body)
n_features = 0
n_entities = 0
parsed_any = False    # a GENERATED marker on both docs means a true no-op

fs_path = os.path.join(readme, "feature-status.md")
if os.path.isfile(fs_path):
    text = read(fs_path)
    if GENERATED in text:
        print("wiki: import skipped readme/feature-status.md (GENERATED marker)")
    else:
        parsed_any = True
        lines = text.splitlines()
        hdr_i, cols = None, []
        for i, ln in enumerate(lines):
            if ln.lstrip().startswith("|"):
                cs = cells(ln)
                low = [c.lower() for c in cs]
                if "feature" in low and "status" in low:
                    hdr_i, cols = i, low
                    break
        if hdr_i is None:
            print("wiki: import found no feature table in readme/feature-status.md")
        else:
            for ln in lines[hdr_i + 1:]:
                if not ln.lstrip().startswith("|"):
                    break
                cs = cells(ln)
                if is_separator(cs):
                    continue

                def col(name):
                    if name in cols:
                        idx = cols.index(name)
                        if idx < len(cs):
                            return cs[idx]
                    return ""

                name = col("feature")
                if not name:
                    continue
                fid = slug(name)
                body = ["<!-- imported from readme/feature-status.md -->",
                        "**Row:** " + name]
                desc = col("description")
                deps = col("dependencies")
                lim = col("known limitations")
                if desc:
                    body += ["", "**Description:** " + desc]
                if deps:
                    body += ["", "**Dependencies:** " + deps]
                if lim:
                    body += ["", "**Known limitations:** " + lim]
                section = "\n".join(body) + "\n"
                target, level = match_feature(name, fid)
                if target:
                    print("wiki: match %r -> %s (level %s)" % (name, target, level),
                          file=sys.stderr)
                    level_counts[level] = level_counts.get(level, 0) + 1
                    feature_bodies.setdefault(target, []).append(section)
                    n_features += 1
                else:
                    orphans.append(("feature row", name,
                                    "readme/feature-status.md", section))

sm_path = os.path.join(readme, "state-machines.md")
if os.path.isfile(sm_path):
    text = read(sm_path)
    if GENERATED in text:
        print("wiki: import skipped readme/state-machines.md (GENERATED marker)")
    else:
        parsed_any = True
        lines = text.splitlines()
        h2 = [i for i, ln in enumerate(lines) if re.match(r"^##\s", ln)]
        for k, i in enumerate(h2):
            end = h2[k + 1] if k + 1 < len(h2) else len(lines)
            name = re.sub(r"^##\s+", "", lines[i]).strip()
            if re.match(r"^(table of contents|contents|toc|overview|legend|status|appendix)",
                        name, re.I):
                continue
            seg = "\n".join(lines[i + 1:end])

            m_src = re.search(r"\*\*(?:Source|Table|Location|File):\*\*[^\n]*", seg)

            def section_of(title):
                m = re.search(r"^###\s+[^\n]*" + title + r"[^\n]*\n(.*?)(?=^###\s|\Z)",
                              seg, re.M | re.S | re.I)
                return m.group(1).strip() if m else ""

            states = section_of("State")
            trans = section_of("Transition")
            body = ["<!-- imported from readme/state-machines.md -->",
                    "", "**Imported entity:** " + name]
            if m_src:
                body += ["", m_src.group(0)]
            if states:
                body += ["", "### States", "", states]
            if trans:
                body += ["", "### Transitions", "", trans]
            section = "\n".join(body) + "\n"
            norm = slug(re.sub(r"^\d+\.?\s*", "", name))
            target, level = match_feature(name, norm)
            if target:
                print("wiki: match %r -> %s (level %s)" % (name, target, level),
                      file=sys.stderr)
                level_counts[level] = level_counts.get(level, 0) + 1
                entity_bodies.setdefault(target, []).append(section)
                n_entities += 1
            else:
                orphans.append(("entity", name, "readme/state-machines.md", section))

os.makedirs(blocks_dir, exist_ok=True)


def write_blocks(mapping, prefix):
    for key, sections in mapping.items():
        path = os.path.join(blocks_dir, prefix + key + ".md")
        with open(path, "w", encoding="utf-8") as fh:
            fh.write("\n".join(sections))


write_blocks(feature_bodies, "")
write_blocks(entity_bodies, "entity-")

# unmatched rows become numbered orphan blocks so generation can embed them
# verbatim in the projections (zero-content-loss); this import owns the
# orphan-* namespace, so stale ones from an earlier run are removed first.
# Gated on parsed_any: a marker no-op must not touch existing blocks.
if parsed_any:
    for old in glob.glob(os.path.join(blocks_dir, "orphan-*.md")):
        os.remove(old)
    for i, (kind, name, origin, body) in enumerate(
            [o for o in orphans if o[0] == "feature row"], 1):
        with open(os.path.join(blocks_dir, "orphan-feature-%d.md" % i),
                  "w", encoding="utf-8") as fh:
            fh.write(body)
    for i, (kind, name, origin, body) in enumerate(
            [o for o in orphans if o[0] == "entity"], 1):
        with open(os.path.join(blocks_dir, "orphan-entity-%d.md" % i),
                  "w", encoding="utf-8") as fh:
            fh.write(body)

if parsed_any and orphans:
    out = ["# Unmatched wiki imports", "",
           "Hand-written doc rows that matched no feature fid in",
           ".wiki/store.json. Their content is carried verbatim in the",
           "generated projections appendix (orphan-* blocks in",
           ".wiki/enrich/blocks/); this ledger is rewritten on every import.",
           ""]
    for kind, name, origin, body in orphans:
        out += ["## %s (%s, %s)" % (name, kind, origin), "", body.rstrip(), ""]
    with open(orphans_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))
elif os.path.isfile(orphans_path):
    os.remove(orphans_path)

levels = " ".join("%s=%d" % (k, level_counts[k]) for k in sorted(level_counts))
print("wiki: imported %d feature rows, %d entities, %d orphans (%s) (blocks: %s)"
      % (n_features, n_entities, len(orphans), levels or "no matches", blocks_dir))
PY
}
