"""Generate Markdown from the same resolved model used by the portal."""
import json
from pathlib import Path
import re
import sys
from datetime import date
from knowledge import model, capability_markdown, STATUSES


def cell(value):
    if isinstance(value, list): value = '; '.join(value)
    return re.sub(r'\s+', ' ', str(value)).replace('|', '\\|').strip() or '-'


def generate(store_path, repo, mode):
    store_path, repo = Path(store_path), Path(repo)
    store = json.loads(store_path.read_text())
    data = model(store_path)
    resolved = store_path.parent / 'enrich/resolved'
    fp = store['meta']['fingerprint']
    header = f'<!-- GENERATED by cfn-wiki sync. Edit knowledge.json or wiki:enrich blocks. -->\n<!-- wiki-fp: {fp} -->\n\n'
    def block(fid):
        body = resolved / (fid + '.md')
        stamp = resolved / (fid + '.fp')
        if not body.exists(): return ''
        old_fp = stamp.read_text().strip() if stamp.exists() else fp
        return f'<!-- wiki:enrich id={fid} fp={old_fp} -->\n{body.read_text().strip()}\n<!-- /wiki:enrich -->\n'
    def install(path, text):
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp = path.with_suffix(path.suffix + '.tmp')
        tmp.write_text(text + '\n')
        tmp.replace(path)
    def appendix(kind):
        blocks = sorted(resolved.glob('orphan-' + kind + '-*.md'))
        if kind == 'entity': blocks += sorted(resolved.glob('entity-*.md'))
        if not blocks: return ''
        return '\n## Appendix. Preserved notes awaiting review\n\nThese legacy notes are preserved for reconciliation; they are not current runtime models.\n\n' + '\n'.join(block(p.stem) for p in blocks)
    if mode == 'projections':
        meanings = ['Live, verified, monitored. Real users.', 'Feature-complete, under verification.', 'In development or not yet assessed.', 'Scaffold only.', 'Scheduled for removal.']
        text = header + '# Feature Status\n\n**Last Updated:** ' + date.today().isoformat() + ' wiki sync\n\n## Status Legend\n\n| Status | Meaning |\n|---|---|\n'
        text += '\n'.join('| ' + s + ' | ' + m + ' |' for s, m in zip(STATUSES, meanings)) + '\n\n'
        text += 'Authored capabilities come first. Directory entries are an inventory, not independently verified product features.\n\n'
        text += '| Feature | Status | Description | Dependencies | Known Limitations |\n|---|---|---|---|---|\n'
        for f in data['features']:
            desc = f['description'] or 'Directory inventory; purpose not yet documented.'
            limits = f.get('limitations') or f['status_reason']
            if isinstance(limits, list):
                limits = limits[0] + ' See the capability page for full limits.'
            if f['needs_review']: limits = 'Source changed; explanation needs review. ' + cell(limits)
            text += '| ' + ' | '.join(cell(v) for v in [f['name'], f['status'], desc, f.get('dependencies', ''), limits]) + ' |\n'
        if not data['features']: text += '\nNo features extracted yet.\n'
        text += '\n## Feature Notes\n\n'
        for f in data['features']:
            text += '### ' + f['name'] + '\n\n'
            if f['kind'] == 'capability':
                text += '[Read the execution flow](wiki/' + f['fid'] + '/wiki.md). ' + f['status_reason'] + '\n\n'
            else: text += block(f['fid']) + '\n'
        text += appendix('feature')
        if len(text.splitlines()) > 300:
            rollup = '## Status Rollup\n\n| Status | Features |\n|---|---|\n' + '\n'.join(f'| {s} | {sum(f["status"] == s for f in data["features"])} |' for s in STATUSES) + '\n\n'
            text = text.replace('## Status Legend', rollup + '## Status Legend', 1)
        install(repo / 'readme/feature-status.md', text)
        text = header + '# State Machines\n\n**Last Updated:** ' + date.today().isoformat() + ' wiki sync\n\n'
        if not data['entities']:
            text += 'No runtime state machines have been documented with source evidence yet. Feature maturity is not runtime state.\n'
        for i, e in enumerate(data['entities'], 1):
            cap = next(f for f in data['features'] if f['fid'] == e['capability'])
            text += f'## {i}. {e["name"]}\n\n**Source:** {e["source"]}\n\n' + e.get('description', '') + '\n\n'
            if cap['needs_review']: text += 'Source changed; review this model before relying on it.\n\n'
            text += '### States\n\n| State | Meaning |\n|---|---|\n'
            text += '\n'.join('| ' + cell(s) + ' | ' + cell(e.get('meanings', {}).get(s, s)) + ' |' for s in e['states']) + '\n\n'
            text += '### Transitions\n\n| From | To | Trigger | Guard |\n|---|---|---|---|\n'
            text += '\n'.join('| ' + ' | '.join(cell(t[k]) for k in ('from', 'to', 'trigger', 'guard')) + ' |' for t in e['transitions']) + '\n\n'
            # Stable Mermaid aliases permit arbitrary display names without injecting syntax.
            aliases = {s: 's' + str(j) for j, s in enumerate(e['states'])}
            aliases['[*]'] = '[*]'
            text += '### Diagram\n\n```mermaid\nstateDiagram-v2\n'
            for s in e['states']:
                text += '  state ' + json.dumps(s) + ' as ' + aliases[s] + '\n'
            for t in e['transitions']:
                text += '  ' + aliases[t['from']] + ' --> ' + aliases[t['to']] + '\n'
            text += '```\n\n'
        text += appendix('entity')
        if len(text.splitlines()) > 300:
            toc = '## Table of Contents\n\n' + '\n'.join(f'- [{i}. {e["name"]}](#{i}-' + re.sub('[^a-z0-9]+', '-', e['name'].lower()).strip('-') + ')' for i, e in enumerate(data['entities'], 1)) + '\n\n'
            text = text.replace('## 1.', toc + '## 1.', 1) if data['entities'] else text.replace('## Appendix', toc + '## Appendix', 1)
        install(repo / 'readme/state-machines.md', text)
    else:
        cfgpath = repo / '.wiki/config.json'
        cfg = json.loads(cfgpath.read_text()) if cfgpath.exists() else {}
        pages = repo / cfg.get('features_dir', 'readme/wiki')
        if not pages.resolve().is_relative_to(repo.resolve()): raise ValueError('features_dir escapes repo')
        for f in data['features']:
            text = header + '# ' + f['name'] + '\n\n**Status:** ' + f['status'] + '\n\n' + f['status_reason'] + '\n\n'
            if f['needs_review']: text += '**Review needed:** Source contents changed since this explanation was reviewed.\n\n'
            text += '**Source:**\n\n' + '\n'.join('- `' + p + '`' for p in f['files']) + '\n\n'
            if f['kind'] == 'capability':
                text += '<!-- wiki:enrich id=' + f['fid'] + ' fp=' + fp + ' -->\n' + capability_markdown(f) + '\n<!-- /wiki:enrich -->\n'
            else:
                text += block(f['fid']) + '\n## Change Coupling\n\n'
                pairs = [p for p in store.get('coupling', []) if set(f['files']).intersection(p['files'])]
                text += '\n'.join('- ' + ', '.join('`' + x + '`' for x in p['files']) + ': ' + str(p['count']) + ' commits' for p in pairs) if pairs else 'No co-change pairs recorded for these files.'
            install(pages / f['fid'] / 'wiki.md', text)
    print('wiki: generated ' + mode)


if __name__ == '__main__':
    generate(*sys.argv[1:])
