/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_messageserializer_free: (a: number, b: number) => void;
export const messageserializer_new: () => number;
export const messageserializer_deserializeMessage: (a: number, b: number, c: number, d: number) => void;
export const messageserializer_batchDeserialize: (a: number, b: number, c: number, d: number) => void;
export const messageserializer_isValidJson: (a: number, b: number, c: number) => number;
export const messageserializer_estimateSize: (a: number, b: number, c: number) => void;
export const messageserializer_serializeCompact: (a: number, b: number, c: number) => void;
export const messageserializer_serializePretty: (a: number, b: number, c: number) => void;
export const messageserializer_clearBuffer: (a: number) => void;
export const messageserializer_getBufferCapacity: (a: number) => number;
export const quickSerialize: (a: number, b: number) => void;
export const quickDeserialize: (a: number, b: number, c: number) => void;
export const __wbg_stateserializer_free: (a: number, b: number) => void;
export const stateserializer_new: (a: number) => number;
export const stateserializer_serializeState: (a: number, b: number, c: number) => void;
export const stateserializer_deserializeState: (a: number, b: number, c: number, d: number) => void;
export const stateserializer_batchSerializeStates: (a: number, b: number, c: number, d: number) => void;
export const stateserializer_statesEqual: (a: number, b: number, c: number, d: number, e: number) => number;
export const stateserializer_getStateSize: (a: number, b: number, c: number) => void;
export const quickSerializeState: (a: number, b: number) => void;
export const quickDeserializeState: (a: number, b: number, c: number) => void;
export const messageserializer_serializeMessage: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
